INSERT INTO POI (NOME, COORDX, COORDY) VALUES ('Lanchonete', 27, 12);
INSERT INTO POI (NOME, COORDX, COORDY) VALUES ('Posto', 31, 18);
INSERT INTO POI (NOME, COORDX, COORDY) VALUES ('Joalheria', 15, 12);
INSERT INTO POI (NOME, COORDX, COORDY) VALUES ('Floricultura', 19, 21);
INSERT INTO POI (NOME, COORDX, COORDY) VALUES ('Pub', 12, 8);
INSERT INTO POI (NOME, COORDX, COORDY) VALUES ('Supermercado', 23, 6);
INSERT INTO POI (NOME, COORDX, COORDY) VALUES ('Churrascaria', 28, 2);